DROP DATABASE IF EXISTS burgers_DB;
CREATE DATABASE burgers_DB;

USE burgers_DB;

CREATE TABLE burgers(
  id INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(150) NOT NULL,
  devoured TINYINT DEFAULT 0,
  PRIMARY KEY (id)
);
